### ISSUE TITLE
SSL handshake error: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:1408F09C:SSL routines:ssl3_get_record:http request

### ISSUE THREAD

**Issue by a-M-i-T** [jsanahuja/php-peer-server#1]
Hello there,
I having this issue while starting the server.. I dont know what I am missing here? Probably with the configs. I even whitelisted the PORT  8999/tcp. Any solution would be helpful. Thanks.

![image](https://user-images.githubusercontent.com/28892420/117412950-1c6d8880-af35-11eb-968e-fbde046842e3.png)

![image](https://user-images.githubusercontent.com/28892420/117413035-360ed000-af35-11eb-844a-d270be30b47a.png)

**Comment by jsanahuja** [comment]
The server.php does not provide an HTTP server but a SocketIO server. Static files such as HTML should be served by an HTTP server.
