### ISSUE TITLE
Sowe\PHPPeerServer with PHP 8.x

### ISSUE THREAD

**Issue by zipelkopf** [jsanahuja/php-peer-server#2]
Hi, when I run the composer it complaints that Sowe\PHPPeerServer requires ^7.1 while I'm on 8.x
Any suggestion other than downgrading my PHP, which I wouldn't like?

Thanks

**Comment by zipelkopf** [comment]
P.S.
I understand that on 8.x it might not be stable but I'm happy to test that :-)
Cheers

**Comment by topsecret-chat-admin** [comment]
Thanks anyway, I found the composer command to skip the requirement contraints

`composer install --ignore-platform-reqs`

Over an out :-)

**Comment by jsanahuja** [comment]
I have updated [sowe/framework](https://github.com/jsanahuja/Sowe-Framework) to support 8.x at [1.5.4](https://github.com/jsanahuja/Sowe-Framework/releases/tag/1.5.4) and tested this repository with Composer 2.2.12 and PHP 8.1.5. If you encounter any problem, please let me know
